<?php

/**
 * @file
 * Contains ngf_search.module.
 */

use Drupal\views\ViewExecutable;

function ngf_search_views_pre_render(ViewExecutable $view) {
    $group_access_manager = \Drupal::getContainer()->get('ngf_group.group_access_manager');
    if ($view->id() == 'ngf_publications_search') {
      foreach ($view->result as $key => $resultRow) {
        if (!$group_access_manager->checkNode($resultRow->_entity)) {
          unset($view->result[$key]);
        }
      }
    }

    if ($view->id() == 'ngf_groups_search') {
      foreach ($view->result as $key => $resultRow) {
        if (!$group_access_manager->checkGroup($resultRow->_entity)) {
          unset($view->result[$key]);
        }
      }
    }
}
