<?php

/**
 * @file
 * Contains ngf_search.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;

function ngf_search_views_pre_render(ViewExecutable $view) {
    $group_access_manager = \Drupal::getContainer()->get('ngf_group.group_access_manager');
    if ($view->id() == 'ngf_publications_search') {
      foreach ($view->result as $key => $resultRow) {
        if (!$group_access_manager->checkNode($resultRow->_entity)) {
          unset($view->result[$key]);
        }
      }
    }

    if ($view->id() == 'ngf_groups_search') {
      foreach ($view->result as $key => $resultRow) {
        if (!$group_access_manager->checkGroup($resultRow->_entity)) {
          unset($view->result[$key]);
        }
      }
    }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ngf_search_form_views_exposed_form_alter(
  &$form,
  FormStateInterface $form_state,
  $form_id
) {
//  var_dump($form);
}
