<?php

/**
 * @file
 * Contains ngf_user_list.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function ngf_user_list_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ngf_user_list module.
    case 'help.page.ngf_user_list':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('NGF User list') . '</p>';
      return $output;

    default:
  }
}

function ngf_user_list_ngf_user_list_view(
    array &$build,
    EntityInterface $entity,
    EntityViewDisplayInterface $display,
    $view_mode
) {
    $response = new RedirectResponse(Url::fromRoute('ngf_user_list.list_items', ['ngf_user_list' => $entity->id()])->toString());
    $response->send();
}