<?php

/**
 * @file
 * Contains ngf_user_list.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ngf_user_list_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ngf_user_list module.
    case 'help.page.ngf_user_list':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('NGF User list') . '</p>';
      return $output;

    default:
  }
}
