<?php

/**
 * @file
 * Contains ngf_geo.module.
 */

/**
 * Implements hook_migration_plugins_alter().
 */
function ngf_geo_migration_plugins_alter(&$definitions) {
  $migrations = [
    'ngf_countries',
    'ngf_regions',
    'ngf_cities'
  ];

  foreach ($migrations as $migration) {
    $definitions[$migration]['source']['path'] = drupal_get_path('module', 'ngf_geo') . $definitions[$migration]['source']['path'];
  }
}
