<?php

use Drupal\Core\Link;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\views\Views;

/**
* Implements hook_entity_extra_field_info().
*/
function ngf_content_entity_extra_field_info() {
  $extra = [];

  $extra['node']['ngf_discussion']['display']['show_more'] = [
    'label' => t('Show more'),
    'description' => t('Displays link show more items'),
    'weight' => 100,
    'visible' => TRUE,
  ];

  $extra['node']['ngf_discussion']['display']['related_content'] = [
    'label' => t('Block: related content'),
    'description' => t('Displays related content'),
    'weight' => 100,
    'visible' => TRUE,
  ];

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function ngf_content_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'ngf_discussion' ) {
    // Show more link.
    if ($display->getComponent('show_more')) {
      $build['show_more'] = [
        '#type' => 'link',
        '#url' => $entity->toUrl(),
        '#title' => t('More')
      ];
    }

    if ($view_mode == 'full') {
      // Related content.
      if ($display->getComponent('related_content')) {
        $view = Views::getView('ngf_discussion_related_content');
        if (is_object($view)) {
          $args = ['parent_id' => $entity->id()];
          $view->setArguments($args);
          $view->setDisplay('block');
          $view->preExecute();
          $view->execute();

          $render = $view->buildRenderable('block', $args);
          $label = '<div class="related-content">Follow up</div>';
          $build['related_content'] = [
            '#type' => 'markup',
            '#label' => 'Above Label',
            '#markup' => $label . render($render),
          ];
        }
      }
    }
  }
}
